version: "3.9"

services:
  tagmanager:
    build: .
    container_name: tagmanager
    ports:
      - "3838:3838"
    environment:
      HTTP_ADDR: ":3838"
      SAYMON_CONFIG_PATH: "/etc/saymon/saymon-server.conf"
      TAGS_COLLECTION: "tags"
      DEBUG_REQUEST_LOGS: "false"
      AUTH_HTTP_TLS_INSECURE_SKIP_VERIFY: "false"
    volumes:
      - /etc/saymon/saymon-server.conf:/etc/saymon/saymon-server.conf:ro
    restart: unless-stopped
